name: Google Chat Actions

on:
  workflow_call:
    inputs:
      header_image:
        description: "Custom header image URL (optional)"
        default: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        required: false
        type: string
      reply_option:
        description: "new_thread or same_thread (optional, default same_thread)"
        default: 'same_thread'
        required: false
        type: string
    secrets:
      notify_pr_webhook:
        description: "Google Chat webhook URL to notify Pull Requests events"
        required: true

jobs:
  notify-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Prepare message
        id: prepare_message
        run: |
          if [ "${{ inputs.reply_option }}" == "new_thread" ]; then
            REPLY_OPTION="MESSAGE_REPLY_OPTION_UNSPECIFIED"
          else
            REPLY_OPTION="REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD"
          fi

          PR_TITLE=$(echo '${{ github.event.pull_request.title }}' | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | jq -n --arg text "$(cat)" -r '$text')
          
          case "${{ github.event.action }}" in
            opened)
              if [ "${{ github.event.pull_request.draft }}" == "true" ]; then
                echo "Notification skipped because the trigger is a draft PR creation"
                exit 0
              else
                HEADER_IMAGE="${{ inputs.header_image }}"
                HEADER_TITLE="📌 Pull Request Created"
                HEADER_SUBTITLE=""
                MESSAGE+="🔗 <b>Repository:</b> ${{ github.repository }}<br/>"
                MESSAGE+="📄 <b>Title:</b> $PR_TITLE<br/>"
                MESSAGE+="👤 <b>Author:</b> @${{ github.actor }}"
              fi
              ;;
            reopened)
              HEADER_TITLE=""
              HEADER_SUBTITLE="🔓 @${{ github.actor }} reopened the PR"
              ;;
            ready_for_review)
              HEADER_IMAGE="${{ inputs.header_image }}"
              HEADER_TITLE="🚀 Pull Request Ready for Review"
              HEADER_SUBTITLE=""
              MESSAGE+="🔗 <b>Repository:</b> ${{ github.repository }}<br/>"
              MESSAGE+="📄 <b>Title:</b> $PR_TITLE<br/>"
              MESSAGE+="👤 <b>Author:</b> @${{ github.actor }}"
              ;;
            converted_to_draft)
              HEADER_TITLE=""
              HEADER_SUBTITLE="📝 @${{ github.actor }} converted the PR to draft"
              ;;
            *)
              HEADER_TITLE="📌 Pull Request Event"
              HEADER_SUBTITLE=""
              MESSAGE+="👤 <b>Author:</b> @${{ github.actor }}"
              ;;
          esac
          
          echo "REPLY_OPTION=$REPLY_OPTION" >> $GITHUB_ENV
          echo "HEADER_TITLE=$HEADER_TITLE" >> $GITHUB_ENV
          echo "HEADER_SUBTITLE=$HEADER_SUBTITLE" >> $GITHUB_ENV
          echo "HEADER_IMAGE=$HEADER_IMAGE" >> $GITHUB_ENV
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Send PR Notification to Google Chat
        id: send_notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "cardsV2": [{
                  "cardId": "pr-notification",
                  "card": {
                    "header": {
                      "title": "'"$HEADER_TITLE"'",
                      "subtitle": "'"$HEADER_SUBTITLE"'",
                      "imageUrl": "'"$HEADER_IMAGE"'"
                    },
                    "sections": [{
                      "widgets": [{
                        "textParagraph": {
                          "text": "'"$MESSAGE"'"
                        }
                      }]
                    },
                    {
                      "widgets": [{
                        "buttonList": {
                          "buttons": [{
                            "text": "🔍 View Pull Request",
                            "onClick": {
                              "openLink": {
                                "url": "'"${{ github.event.pull_request.html_url }}"'"
                              }
                            }
                          }]
                        }
                      }]
                    }]
                  }
                }],
                "thread": {
                  "threadKey": "'"${{ github.repository }}/${{ github.event.pull_request.number }}"'"
                }
              }' \
          "${{ secrets.notify_pr_webhook }}&messageReplyOption=$REPLY_OPTION"

  notify-pr-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review' || github.event_name == 'issue_comment'
    steps:
      - name: Prepare message
        id: prepare_message
        run: |
          if [ "${{ inputs.reply_option }}" == "new_thread" ]; then
            REPLY_OPTION="MESSAGE_REPLY_OPTION_UNSPECIFIED"
          else
            REPLY_OPTION="REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD"
          fi
          
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            HEADER_SUBTITLE="💬 @${{ github.actor }} left a comment"
            BUTTON_TEXT="🔍 View Comment"
            BUTTON_URL="${{ github.event.comment.html_url }}"
            COMMENT="$(echo '${{ github.event.comment.body }}' | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | jq -n --arg text "$(cat)" -r '$text')"
            PR_NUMBER=$(echo "${{ github.event.comment.html_url }}" | sed 's/.*pull\/\([0-9]*\).*/\1/')
          else
            BUTTON_URL="${{ github.event.review.html_url }}"
            COMMENT="$(echo '${{ github.event.review.body }}' | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | jq -n --arg text "$(cat)" -r '$text')"
            PR_NUMBER="${{ github.event.pull_request.number }}"
            case "${{ github.event.review.state }}" in
              approved)
                HEADER_SUBTITLE="✅ @${{ github.actor }} approved the PR"
                BUTTON_TEXT="🔍 View Approval"
                ;;
              commented)
                HEADER_SUBTITLE="💬 @${{ github.actor }} left a comment"
                BUTTON_TEXT="🔍 View Comment"
                ;;
              changes_requested)
                HEADER_SUBTITLE="❌ @${{ github.actor }} requested changes"
                BUTTON_TEXT="🔍 View Requested Changes"
                ;;
              *)
                HEADER_SUBTITLE="📌 @${{ github.actor }} reviewed"
                BUTTON_TEXT="🔍 View Event"
                ;;
            esac
          fi
                    
          echo "REPLY_OPTION=$REPLY_OPTION" >> $GITHUB_ENV
          echo "HEADER_SUBTITLE=$HEADER_SUBTITLE" >> $GITHUB_ENV
          echo "BUTTON_TEXT=$BUTTON_TEXT" >> $GITHUB_ENV
          echo "BUTTON_URL=$BUTTON_URL" >> $GITHUB_ENV
          echo "COMMENT=$COMMENT" >> $GITHUB_ENV
          echo "THREAD_KEY=${{ github.repository }}/$PR_NUMBER" >> $GITHUB_ENV

      - name: Send Notification to Google Chat
        id: send_notification
        run: |
          JSON_PAYLOAD='{
            "cardsV2": [{
              "cardId": "pr-notification",
              "card": {
                "header": {
                  "subtitle": "'"$HEADER_SUBTITLE"'"
                },
                "sections": [{
                  "widgets": [{
                    "buttonList": {
                      "buttons": [{
                        "text": "'"$BUTTON_TEXT"'",
                        "onClick": {
                          "openLink": {
                            "url": "'"$BUTTON_URL"'"
                          }
                        }
                      }]
                    }
                  }'

          if [ -n "$COMMENT" ]; then
            JSON_PAYLOAD+=',{
              "textParagraph": {
                  "text": "'"$COMMENT"'",
                  "maxLines": 5
                }
              }'
          fi
            
          JSON_PAYLOAD+=']'

          if [ -n "$COMMENT" ]; then
            JSON_PAYLOAD+=',
              "collapsible": true,
              "collapseControl": {
                "horizontalAlignment": "CENTER",
                "collapseButton": {
                  "icon": {
                    "materialIcon": {
                      "name": "visibility_off"
                    }
                  },
                  "text": "Hide comment",
                  "type": "BORDERLESS"
                },
                "expandButton": {
                  "icon": {
                    "materialIcon": {
                      "name": "visibility"
                    }
                  },
                  "text": "Preview comment",
                  "type": "BORDERLESS"
                }
              },
              "uncollapsibleWidgetsCount": 1'
          fi

          JSON_PAYLOAD+='}]}}],
            "thread": {
              "threadKey": "'"$THREAD_KEY"'"
            }
          }'

          echo "$JSON_PAYLOAD" | curl -X POST -H "Content-Type: application/json" -d @- \
          "${{ secrets.notify_pr_webhook }}&messageReplyOption=$REPLY_OPTION"

  notify-opened-prs:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Fetch Open PRs via GitHub API
        id: fetch_open_prs
        run: |
          echo "pre response"
          RESPONSE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")

          echo "post response"
          echo "$RESPONSE"

          # Verifica se a resposta é um JSON válido
          if ! echo "$RESPONSE" | jq empty; then
            echo "❌ Erro: Resposta inválida da API do GitHub"
            echo "API Response: $RESPONSE"
            exit 1
          fi
          
          echo "PR list is not empty"
    
          PR_COUNT=$(echo "$RESPONSE" | jq '. | length')
          
          if [ "$PR_COUNT" -eq 0 ]; then
            echo "No open PRs, skipping notification."
            exit 0
          fi
          
          echo "creating message...."
          
          PR_MESSAGE=""
          for row in $(echo "$RESPONSE" | jq -r '.[] | @base64'); do
            _jq() { echo ${row} | base64 --decode | jq -r ${1}; }
            PR_TITLE=$(_jq '.title' | sed 's/"/\\"/g')  # Escapar aspas duplas
            PR_URL=$(_jq '.html_url')
            PR_MESSAGE+="🔹 <b>$PR_TITLE</b><br/><a href='$PR_URL'>$PR_URL</a><br/><br/>"
          done
          
          echo "message build!"
          
          echo "PR_MESSAGE=$PR_MESSAGE" >> $GITHUB_ENV

      - name: Send Open PRs Report to Google Chat
        run: |
          echo "Starting job..."
          
          if [ "${{ inputs.reply_option }}" == "new_thread" ]; then
            REPLY_OPTION="MESSAGE_REPLY_OPTION_UNSPECIFIED"
          else
            REPLY_OPTION="REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD"
          fi
          
          echo "reply option: $REPLY_OPTION"
          
          ESCAPED_MESSAGE=$(echo "$PR_MESSAGE" | jq -Rs '.')
          echo "msg: $ESCAPED_MESSAGE"
          
          THREAD_KEY=$(date -u +'%Y-%m-%d')
          echo "thread key: $THREAD_KEY"
          
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "cardsV2": [{
                  "cardId": "open-prs-report",
                  "card": {
                    "header": {
                      "title": "📢 Open Pull Requests Report",
                      "subtitle": "Weekly Summary",
                      "imageUrl": "'"${{ inputs.header_image }}"'"
                    },
                    "sections": [{
                      "collapsible": true,
                      "collapseControl": {
                        "horizontalAlignment": "CENTER",
                        "collapseButton": {
                          "icon": {
                            "materialIcon": {
                              "name": "visibility_off"
                            }
                          },
                          "text": "Esconder lista",
                          "type": "BORDERLESS"
                        },
                        "expandButton": {
                          "icon": {
                            "materialIcon": {
                              "name": "visibility"
                            }
                          },
                          "text": "Mostrar lista",
                          "type": "BORDERLESS"
                        }
                      },
                      "uncollapsibleWidgetsCount": 0,
                      "widgets": [{
                        "textParagraph": {
                          "text": "dfff"
                        }
                      }]
                    }]
                  }
                }],
                "thread": {
                   "threadKey": "'"$THREAD_KEY"'"
                }
              }' \
          "${{ secrets.notify_pr_webhook }}&messageReplyOption=$REPLY_OPTION"
